apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: prometheus
roleRef:
  kind: ClusterRole 
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io