apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob
subjects:
- kind: ServiceAccount 
  name: bob
  apiGroup: ""
roleRef:
  kind: ClusterRole 
  name: admin
  apiGroup: rbac.authorization.k8s.io