apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: wordpress
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: wordpress
  name: pod-launcher
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wp-rolebinding
  namespace: wordpress
subjects:
- kind: ServiceAccount
  name: wordpress
  apiGroup: ""
  namespace: wordpress
roleRef:
  kind: Role 
  name: pod-launcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress
  annotations:
    kubernetes.io/service-account.name: wordpress
type: kubernetes.io/service-account-token