apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: default
  labels: { k8s-app: prometheus, component: node-exporter }
spec:
 # Стратегия обновления Podов
  #updateStrategy: OnDelete
  selector:
    matchLabels: { k8s-app: prometheus, component: node-exporter }
  template:
    metadata:
      name: node-exporter
      labels: { k8s-app: prometheus, component: node-exporter }
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-exporter
        image: bitnami/node-exporter:latest
        ports:
        - containerPort: 9100
          protocol: TCP