apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    tier: payment
spec:
  # modify replicas according to your case
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 33%
  selector:
    matchLabels:
      tier: payment
  template:
    metadata:
      labels:
        tier: payment
    spec:
      containers:
      - name: payment-service
        image: salvasser/payment:v0.0.1
        env:
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"